# Generated by Django 3.2.8 on 2023-08-11 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('company', '0001_initial'),
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=30, unique=True)),
                ('offer_title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('salary', models.FloatField()),
                ('date_hire', models.CharField(max_length=13)),
                ('number_vacancies', models.IntegerField()),
                ('years_experience', models.FloatField()),
                ('age_start', models.IntegerField()),
                ('age_end', models.IntegerField()),
                ('availability_travel', models.IntegerField()),
                ('change_residence', models.IntegerField()),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.area')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company.company')),
                ('driving_license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driving_license', to='setting.driving_license')),
                ('languages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='setting.languages')),
                ('languages_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages_level', to='setting.languages_level')),
                ('minimum_studies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minimum_studies', to='setting.minimum_studies')),
                ('municipalities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='setting.municipalities')),
                ('type_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_contract', to='setting.type_contract')),
                ('workday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workday', to='setting.workday')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplace', to='setting.workplace')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_date', models.DateTimeField(auto_now_add=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='operation.publication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.user')),
            ],
        ),
    ]
