# Generated by Django 3.2.8 on 2023-08-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='user',
        ),
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.ManyToManyField(related_name='publications_applied', to='user.User'),
        ),
    ]
