# Generated by Django 3.2.8 on 2023-08-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_alter_type_contract_name'),
        ('operation', '0004_alter_publication_change_residence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='driving_license',
        ),
        migrations.AddField(
            model_name='publication',
            name='driving_license',
            field=models.ManyToManyField(related_name='driving_license', to='setting.Driving_License'),
        ),
    ]
