DATA = [
        "Administración / Oficina",
        "Almacén / Logística / Transporte",
        "Atención a clientes",
        "CallCenter / Telemercadeo",
        "Compras / Comercio Exterior",
        "Construcción y obra",
        "Contabilidad / Finanzas",
        "Dirección / Gerencia",
        "Diseño / Artes gráficas",
        "Docencia",
        "Hostelería / Turismo",
        "Informática / Telecomunicaciones",
        "Ingeniería",
        "Investigación y Calidad",
        "Legal / Asesoría",
        "Mantenimiento y Reparaciones Técnicas",
        "Medicina / Salud",
        "Mercadotecnia / Publicidad / Comunicación",
        "Otros",
        "Producción / Operarios / Manufactura",
        "Recursos Humanos",
        "Servicios Generales, Aseo y Seguridad",
        "Ventas"
    ]

LENGUAGES = [
    "Español",
    "Inglés",
    "Portugués",
    "Ruso",
    "Árabe",
    "Chino",
    "Chino Cantones",
    "Francés",
    "Alemán",
    "Abjaso",
    "Afar",
    "Afrikaans",
    "Aimara",
    "Akano",
    "Albanés",
    "Amárico",
    "Aragonés",
    "Armenio",
    "Asamés",
    "Avar",
    "Avéstico",
    "Azerí",
    "Bambara",
    "Baskir",
    "Bengalí",
    "Bhojpurí",
    "Bielorruso",
    "Birmano",
    "Bislama",
    "Bosnio",
    "Bretón",
    "Búlgaro",
    "Cachemiro",
    "Camboyano",
    "Canarés",
    "Catalán",
    "Chamorro",
    "Checheno",
    "Checo",
    "Chichewa",
    "Chuan",
    "Chuvasio",
    "Cingalés",
    "Coreano",
    "Corso",
    "Cree",
    "Croata",
    "Córnico",
    "Danés",
    "Dzongkha",
    "Eslavo",
    "Eslovaco",
    "Esloveno",
    "Esperanto",
    "Estonio",
    "Euskera",
    "Ewe",
    "Feroés",
    "Finés",
    "Fiyiano",
    "Frisón",
    "Fula",
    "Gallego",
    "Galés",
    "Gaélico",
    "Gaélico Escocés",
    "Georgiano",
    "Griego",
    "Groenlandés",
    "Guaraní",
    "Guyaratí",
    "Haitiano",
    "Hausa",
    "Hebreo",
    "Herero",
    "Hindú",
    "Hiri Motu",
    "Húngaro",
    "Ido",
    "Igbo",
    "Indonesio",
    "Interlingua",
    "Inuktitut",
    "Inupiaq",
    "Islandés",
    "Italiano",
    "Japonés",
    "Javanés",
    "Kanuri",
    "Kazajo",
    "Kikuyu",
    "Kirguís",
    "Kirundi",
    "Komi",
    "Kongo",
    "Kuanyama",
    "Kurdo",
    "Lao",
    "Latín",
    "Letón",
    "Limburgués",
    "Lingala",
    "Lituano",
    "Luba-Katanga",
    "Luganda",
    "Luxemburgués",
    "Macedonio",
    "Malayalam",
    "Malayo",
    "Maldivo",
    "Malgache",
    "Maltés",
    "Manés",
    "Maorí",
    "Mapugundun",
    "Maratí",
    "Marshalés",
    "Mongol",
    "Nauruano",
    "Navajo",
    "Ndebele Del Norte",
    "Ndebele Del Sur",
    "Ndonga",
    "Neerlandés",
    "Nepalí",
    "Noruego",
    "Noruego Bokmål",
    "Nynorsk",
    "Occidental",
    "Occitano",
    "Ojibwa",
    "Oriya",
    "Oromo",
    "Osético",
    "Pali",
    "Panyabí",
    "Pastú",
    "Persa",
    "Polaco",
    "Quechua",
    "Romanche",
    "Ruandés",
    "Rumano",
    "Sami Septentrional",
    "Samoano",
    "Sango",
    "Sardo",
    "Serbio",
    "Sesotho",
    "Setsuana",
    "Shona",
    "Sindhi",
    "Somalí",
    "Suajili",
    "Suazi",
    "Sueco",
    "Sundanés",
    "Sánscrito",
    "Tagalo",
    "Tahitiano",
    "Tailandés",
    "Tamil",
    "Tayiko",
    "Telugú",
    "Tibetano",
    "Tigriña",
    "Tongano",
    "Tsonga",
    "Turco",
    "Turcomano",
    "Twi",
    "Tártaro",
    "Ucraniano",
    "Uigur",
    "Urdu",
    "Uzbeko",
    "Valón",
    "Venda",
    "Vietnamita",
    "Volapük",
    "Wolof",
    "Xhosa",
    "Yi De Sichuán",
    "Yoruba",
    "Yídish",
    "Zulú"
  ]