# Generated by Django 3.2.8 on 2023-08-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='Logo_Company/without_logo.png', null=True, upload_to='Logo_Company'),
        ),
    ]
