# Generated by Django 3.2.8 on 2023-08-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone_2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
