# Generated by Django 3.2.8 on 2023-08-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_contract',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
