# Generated by Django 3.2.8 on 2023-08-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_user',
            field=models.IntegerField(default=1),
        ),
    ]
