# Generated by Django 3.2.8 on 2023-08-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_work_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
